name: Deploy version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version which should be deployed, e.g. 1.2.3

env:
  PROJECT_NAME: node-express-kubernetes-example
  ORGANIZATION: juffalow

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Obtain kubernetes config
      env:
        cluster: ${{ secrets.DIGITALOCEAN_KUBERNETES_PRODUCTION }}
      run: doctl kubernetes cluster kubeconfig save $cluster
    - name: Set version
      id: version
      run: echo ::set-output name=tag::${{ github.event.inputs.message }}
    - name: Deploy new version
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run: |
        kubectl set image deployment/$BACKEND_PROJECT_NAME-deployment $BACKEND_PROJECT_NAME-application=registry.digitalocean.com/$ORGANIZATION/$BACKEND_PROJECT_NAME:$VERSION
